### ISSUE TITLE
Can't receive mail from tom.com

### ISSUE THREAD

**Issue by shangdiyisi** [Atlantis-Software/mailx#3]
I can receive mail form tom.com by https://www.npmjs.com/package/poplib

**Comment by atiertant** [comment]
@shangdiyisi look like poplib is no more supported by his author,we included it and rewrote some parts in our code, try using mailx and give us more details if you need some help...

**Comment by shangdiyisi** [comment]
```
'use strict';
var mailx = require('mailx');

var username = 'xxx@tom.com';
var password = 'xxx';
if(username && username.split('@')[1] == 'tom.com') {
    var store = mailx.store('pop3', 'pop.tom.com', 110, username, password);
    store.connect(function(err) {
        if (err) {
            return console.log('connect error', err);
        } else {
            store.getInboxMessages(0, function(err, messages) {
                if (err) {
                    return console.log('inbox error', err);
                } else {
                    messages.forEach(function(message, index) {
                        console.log(message.subject);
                    });
                }
            });
        }
    });
}

connect error Error: -ERR invalid command
at Socket.<anonymous> (/www/nodejs/test/node_modules/mailx/lib/poplib.js:124:17)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:172:18)
at Socket.Readable.push (_stream_readable.js:130:10)
at TCP.onread (net.js:542:20)
```

**Comment by shangdiyisi** [comment]
@atiertant   Had you found the problem?

**Comment by atiertant** [comment]
@shangdiyisi this could be the start tls ... have you got a test account (send it by email not in public)?
witch version of mailx do you use?

**Comment by shangdiyisi** [comment]
@atiertant    I use the newest version of mailx.  Test account had send email to you

**Comment by shangdiyisi** [comment]
@atiertant  Had you received my email and make a test?

**Comment by shangdiyisi** [comment]
Hotmail has problem too.
`connect error Error: Unable to execute STLS as TLS connection already established
    at POP3Client.stls (/www/nodejs/test/node_modules/mailx/lib/poplib.js:378:15)
    at /www/nodejs/test/node_modules/mailx/lib/popStore.js:32:21
    at TLSSocket.<anonymous> (/www/nodejs/test/node_modules/mailx/lib/poplib.js:247:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at TLSSocket.Readable.push (_stream_readable.js:130:10)
    at TLSWrap.onread (net.js:542:20)`

**Comment by atiertant** [comment]
@shangdiyisi i received your email, i'll try to test it this days

**Comment by atiertant** [comment]
@shangdiyisi sorry for the long time, mailx 0.0.11 solve you problem.
