### ISSUE TITLE
 No mailbox is currently selected

### ISSUE THREAD

**Issue by docsmatic** [Atlantis-Software/mailx#5]
Hi ! When i run example 
var store = mailx.store('pop3', 'pop.host.com', 110, 'login', 'password');
store.connect(function(err) {
  if (err) {
    return console.log('connect error', err);
  }
  store.getInboxMessages(0, function(err, messages) {
    if (err) {
      return console.log('inbox error', err);
    }
    messages.forEach(function(message,index) {
      console.log(message.subject);
      if (index === messages.length - 1) {
        message.delete(function(err, data) {
          console.log('message deleted!', data);
          store.close(function(err, data) {
            console.log('store.close err:', err);
          });
        });
      }
    });
  });
});
then i got messages succesfully but got error  No mailbox is currently selected while try to delete message

**Comment by atiertant** [comment]
because you close your store every time you delete a message...
you should delete all your messages before closing the store

**Comment by docsmatic** [comment]
No, store closed after only last message has been deleted. This example copy-pasted from main page of mailx - https://github.com/Atlantis-Software/mailx
