### ISSUE TITLE
Functions to get list of messages (not the content of each) and to subsequently get message

### ISSUE THREAD

**Issue by xcapt** [Atlantis-Software/mailx#6]
Hi,
I like the api of mailx and was looking to use it for a new project, however it seems like the 2 inbox methods: getInboxMessages & getNextMessage automatically fetch attachments.

How can I get a list of message headers first and then i needed fetch the attachment data later if needed ?

**Comment by atiertant** [comment]
@xcapt attachments are part of raw message sent by server so you can't receive them without attachments...

**Comment by xcapt** [comment]
Ah ok noted, thanks.

Turned out my problem with polling could also be solved by an elegant on('mail',....) like in
https://github.com/chirag04/mail-listener2

Thanks!
